sudo: required
services:
    - docker

before_install:
    - docker build -t arpit1294/devops-workflow-react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
    - docker container run -e CI=true arpit1294/devops-workflow-react-test  npm run test -- --coverage


after_success:
    - docker build -t arpit1294/multi-client ./complex/client
    - docker build -t arpit1294/multi-nginx ./complex/nginx
    - docker build -t arpit1294/multi-server ./complex/server
    - docker build -t arpit1294/multi-worker ./complex/worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push arpit1294/multi-client
    - docker push arpit1294/multi-nginx
    - docker push arpit1294/multi-server
    - docker push arpit1294/multi-worker
