apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - image: arpit1294/multi-client
      name: client
      ports:
        - containerPort: 3000
